#Name: Vensan Cabardo
#Date: 1/18/2019
#Course: CS370 Compilers 
#Description:The following makefiles contains the lines necessary for compiling the program.
#This is done so that everytime the lex file is updated, the makefile will run lex and 
#compile the lex result
all:
	lex wordlengthlab1.l
	gcc -o wordlength lex.yy.c


