#Name: Vensan Cabardo
#Date: 1/25/2019
#Course: CS370 Compilers 
#Description: This makefile contains the lines necessary for compiling the program.
#This is done so that everytime the lex and yacc file are updated, the makefile will run lex and yacc and compile the lex result
all:
	lex lab2remove.l
	gcc -o lab2.1 lex.yy.c

